In [3]:
import numpy as np

my_array = np.array([1,2,3,4,3,2,1]) #Bara en datatype, integer

my_array


array([1, 2, 3, 4, 3, 2, 1])

In [10]:
a = np.random.randint(10,20)
a1 = np.ones(10)
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
my_array

array([1, 2, 3, 4, 3, 2, 1])

In [12]:
my_array[[0, -1, 3]]

array([1, 1, 4])